### PR TITLE
Option to *not* wrap in input-group

### PR DESCRIPTION
**Pull request by jpalmieri**
Addresses #25

• Adds an option to _not_ wrap the elements in an input-group
• In this case, it will also append the icon to the parent (rather than inserting it after the text field). This addressed the use case of having an input-group with additional elements (other than the password field, text field, and icon from this library).

If this is acceptable, I can add documentation.

### CODE REVIEW

**Comment by wenzhixin** [comment]
Thanks for your contribution!
It's a useful option, please help to update the documentation.
BTW, we don't need to build the dist, when we release a new version, we will do that.

**Comment by ellisonpatterson** [comment]
@wenzhixin could this get merged? Thank you!

**Comment by jpalmieri** [comment]
Sorry for dropping the ball on this. The branch still needs to add the new option to documentation and remove the `dist` build. Feel free to take that on @ellisonpatterson

**Comment by jpalmieri** [comment]
closing this because I don't want to make it merge-ready, and I have to delete my local repo. I also have no idea how relevant this is anymore

**Pull request closed without merging**
