### PR TITLE
Update to use Bootstrap version 5.x

### PR DESCRIPTION
**Pull request by illuusio**
Update to use Bootstrap version 5.x and keep backward compability with version 4 and 3

### CODE REVIEW

**Comment by illuusio** [comment]
I don't know is this project in active state anymore?

**Comment by hasansezertasan** [comment]
> I don't know is this project in active state anymore?

The author didn't reply to my comment, so we can assume it's an abondenware.

Do you @illuusio know of any alternative to this project?

**Review by wenzhixin — APPROVED** [review]

**Comment by illuusio** [comment]
@wenzhixin I was too rough! Thanks. @hasansezertasan I don't know any as elegant alternative as this.

**Comment by wenzhixin** [comment]
Thanks for your contribution!
I have released a new version.

**Pull request merged**
